steps:
  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/${PROJECT_ID}/training_segmentation_ai:${SHORT_SHA}', '.']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/${PROJECT_ID}/training_segmentation_ai:${SHORT_SHA}']
  # [END cloudbuild_python_push_yaml]
  
  # [START cloudbuild_python_deploy_yaml]
  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'training_segmentation_ai', 
           '--image=gcr.io/${PROJECT_ID}/training_segmentation_ai:${SHORT_SHA}', 
           '--region', 'asia-southeast1', '--platform', 'managed', 
           '--allow-unauthenticated', '--memory', '16Gi', '--cpu', '4',
           '--port', '9001', '--timeout', '3600s', '--concurrency', '20',
           '--min-instances', '0']
  # [END cloudbuild_python_deploy_yaml]

options:
  logging: CLOUD_LOGGING_ONLY
  
# Store images in Google Artifact Registry 
images:
  - gcr.io/${PROJECT_ID}/training_segmentation_ai:${SHORT_SHA}
  
timeout: 3600s
# [END cloudbuild_python_yaml]
