steps:
  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/${PROJECT_ID}/relate_api:${SHORT_SHA}', '.']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/${PROJECT_ID}/relate_api:${SHORT_SHA}']
  # [END cloudbuild_python_push_yaml]
  
  # [START cloudbuild_python_deploy_yaml]
  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'relate-api-74d4560', 
           '--image=gcr.io/${PROJECT_ID}/relate_api:${SHORT_SHA}', 
           '--region', 'asia-southeast1', '--platform', 'managed', 
           '--allow-unauthenticated', '--memory', '4Gi', '--cpu', '2',
           '--port', '9001', '--timeout', '60s', '--concurrency', '20',
           '--min-instances', '1']
  # [END cloudbuild_python_deploy_yaml]

options:
  logging: CLOUD_LOGGING_ONLY
  
# Store images in Google Artifact Registry 
images:
  - gcr.io/${PROJECT_ID}/relate_api:${SHORT_SHA}
# [END cloudbuild_python_yaml]
